### ISSUE TITLE
Compile for windows

### ISSUE THREAD

**Issue by K-ll** [picoflamingo/hacking_codes#1]
Hi,
how can i compile bot.c for windows?
Thx for answer

**Comment by rschmicker** [comment]
bot.c has been written for a UNIX environment, you will have to modify the source code to adjust for Windows. For example unistd.h is a UNIX header. 

When using Windows, you may try to comment out the lines where it is included(and the other UNIX only headers). You will probably get some errors then about missing functions. Check then if the missing functions are defined in other Windows specific header files and include those instead (io.h is a candidate). For functions that does not exist with Windows, check if there are similar functions and use those or just remove the calls. But all these requires that you understand the code.

Alternatively you can search the web for a Windows port of the unistd.h header file (search term 'unistd.h windows replacement').

**Comment by picoflamingo** [comment]
Hi @K-II and @rschmicker

The easiest way to get the code compiled on Windows is to use cygwin. If you really want to port it to use the native windows API you may need to do a couple of things:
- As @rschmicker said you will have to get rid of the Unix specific headers and add the equivalent windows ones. For socket programming you have to use winsock (#include <winsock2.h>) and of course the windows.h header
- Then. most of the socket related calls are the same (BSD interface), however windows functions returns an HRESULT object instead of an integer. You will have to change all the error checks for < -1 to != 0
- Finally, as far as I remember windows does not support to user read and write on sockets, so you will also have to change read to recv and write to send (basically you have to add one extra parameter that will be 0 for bot.c)

It looks like there is a popen function on windows (https://msdn.microsoft.com/en-us/library/96ayss4b(VS.80).aspx), so that part should be straight forward.

Everything else, as far as I can see is standard C that should just work.

Hope this help
